languageCode = "en-us"
title = "bazhenovc"
baseurl = "https://bazhenovc.github.io/blog/"
disqusShortname = "bazhenovcsblog"
googleAnalytics = "UA-111358204-1"
theme = "hugo-dusk"
paginate = 10
canonifyurls = true
copyright = "Copyright (c) 2017, all rights reserved."

[author]
  name = "Kirill Bazhenov"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
PygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
PygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."

[params]
  github = "bazhenovc"
  #gitlab = "gitlab id"
  #twitter = "twitter id"
  #linkedin = "linkedin id"
  email = "bazhenovc@gmail.com"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
